INSERT INTO "Product" (
  "id",
  "name",
  "description",
  "price",
  "originalPrice",
  "imagePath",
  "category",
  "tags",
  "rating",
  "reviewCount",
  "inStock",
  "sizes",
  "colors",
  "isNew",
  "isBestSeller",
  "updatedAt"
) VALUES
  (
    1,
    'Ladies Top',
    'Elegant ladies top crafted with premium fabric. Perfect for casual outings or formal events.',
    150,
    NULL,
    '/products/ladies-top.jpg',
    'Bags',
    '["Top","Fashion"]',
    4.8,
    24,
    true,
    '[]',
    '["Cream","White","Black"]',
    true,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    2,
    'Premium Leather Tote',
    'Elegant leather tote crafted with premium full-grain leather. Spacious interior with multiple compartments, perfect for everyday use.',
    50,
    120,
    '/products/premium-leather-tote.jpg',
    'Bags',
    '["Bags","Leather","Tote"]',
    4.7,
    18,
    true,
    '[]',
    '["Brown","Black","Tan"]',
    false,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    3,
    'Chic Crossbody',
    'Chic crossbody bag with adjustable strap, ideal for hands-free convenience without compromising style.',
    85,
    NULL,
    '/products/chic-crossbody.jpg',
    'Bags',
    '["Bags","Crossbody"]',
    4.6,
    12,
    true,
    '[]',
    '["Black","Caramel"]',
    false,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    4,
    'Luxury Clutch',
    'Luxurious clutch bag with magnetic clasp closure. Perfect companion for formal occasions and date nights.',
    75,
    150,
    '/products/luxury-clutch.jpg',
    'Bags',
    '["Bags","Clutch","Formal"]',
    4.9,
    31,
    true,
    '[]',
    '["Black","Nude","Red"]',
    false,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    5,
    'Classic Shoulder Bag',
    'Timeless shoulder bag with gold-tone hardware. A wardrobe staple that pairs beautifully with any outfit.',
    50,
    95,
    '/products/classic-shoulder-bag.jpg',
    'Bags',
    '["Bags","Shoulder"]',
    4.5,
    9,
    true,
    '[]',
    '["Brown","Black"]',
    false,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    6,
    'Modern Satchel',
    'Structured satchel with top handle and detachable strap. Sophisticated design for the modern professional.',
    100,
    150,
    '/products/modern-satchel.jpg',
    'Bags',
    '["Bags","Satchel","Professional"]',
    4.4,
    7,
    true,
    '[]',
    '["Navy","Black","Burgundy"]',
    false,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    7,
    'Sporty Jersey',
    'High-quality jersey for sports and casual wear. Breathable material and stylish fit.',
    85,
    165,
    '/products/sporty-jersey.jpg',
    'Accessories',
    '["Jersey","Sports"]',
    4.7,
    15,
    true,
    '[]',
    '[]',
    false,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    8,
    'Premium Slippers',
    'Comfortable and stylish slippers for home or outdoor use. Made with durable materials.',
    100,
    200,
    '/products/premium-slippers.jpg',
    'Shoes',
    '["Shoes","Slippers"]',
    4.8,
    22,
    true,
    '[]',
    '[]',
    true,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    9,
    'Luxury Watch',
    'A timeless luxury watch that combines precision and elegance. Water-resistant and crafted with a premium finish.',
    350,
    NULL,
    '/products/luxury-watch.jpg',
    'Watches',
    '["Watches","Luxury","Accessories"]',
    4.9,
    44,
    true,
    '[]',
    '[]',
    true,
    false,
    CURRENT_TIMESTAMP
  ),
  (
    10,
    'Leather Wallet',
    'Slim leather wallet with multiple card slots and cash compartment. Minimalist design for the modern individual.',
    150,
    NULL,
    '/products/leather-wallet.jpg',
    'Wallets',
    '["Wallets","Leather","Slim"]',
    4.6,
    19,
    true,
    '[]',
    '["Brown","Black","Tan"]',
    false,
    false,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "price" = EXCLUDED."price",
  "originalPrice" = EXCLUDED."originalPrice",
  "imagePath" = EXCLUDED."imagePath",
  "category" = EXCLUDED."category",
  "tags" = EXCLUDED."tags",
  "rating" = EXCLUDED."rating",
  "reviewCount" = EXCLUDED."reviewCount",
  "inStock" = EXCLUDED."inStock",
  "sizes" = EXCLUDED."sizes",
  "colors" = EXCLUDED."colors",
  "isNew" = EXCLUDED."isNew",
  "isBestSeller" = EXCLUDED."isBestSeller",
  "updatedAt" = EXCLUDED."updatedAt";
