// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pzElFNXMNqBXDHasJnH5WSHhtsvfd7k',
    appId: '1:24986377031:web:f9cc0d83dcd7151968ca62',
    messagingSenderId: '24986377031',
    projectId: 'commerce-80c74',
    authDomain: 'commerce-80c74.firebaseapp.com',
    storageBucket: 'commerce-80c74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm6ARgwLiFXLmBvhX9M6DjGSk1TDdLQLU',
    appId: '1:24986377031:android:ebf6008ba9398f4268ca62',
    messagingSenderId: '24986377031',
    projectId: 'commerce-80c74',
    storageBucket: 'commerce-80c74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBESoXuv5IWGONZbbQUJkDT9Z_5BRcDhpE',
    appId: '1:24986377031:ios:9595918b967ae44068ca62',
    messagingSenderId: '24986377031',
    projectId: 'commerce-80c74',
    storageBucket: 'commerce-80c74.firebasestorage.app',
    iosBundleId: 'eckintosh.com',
  );
}
